to_lower = True
remove_url=True
remove_time=True
expand_contraction = True
remove_special_character=True
remove_punctuation=True
remove_whitespace=True
keep_alpha_numeric = True
check_spelling=True
remove_stopword=True
lemmatize_word=True
